### PR TITLE
A resilient list decoding operator: <|?|

### PR DESCRIPTION
**Pull request by alcarvalho**
Thinking about how to sove #161 I have come up with this operator.

I think that just omitting items that could not be decoded makes more sense then returning an array of optionals `[T?]`.

I am not sure about how I have named things though.

### CODE REVIEW

**Comment by tonyd256** [comment]
@alcarvalho thanks for making this PR; however, I'd like to stray away from adding more custom operators to Argo. As it is now, there is a lot of resistance to use Argo because of the custom operators and adding one more won't help. That being said, I think you can accomplish what you want without an operator.

First, are you sure that you actually want an array of optionals? This PR doesn't seem to be adding any functionality. It appears that you've added functions with the same type signature as functions that were already in Argo. Even their implementation is the same. Also, the example you use in this PR is not an array of optional `Comment`s but just an array of non-optional `Comment`s which the `<||` operator would be fine for.

Anyways, to accomplish the `[Comment?]` that you want I would do this:
```swift
switch json {
case let .Array(a): return a.map { Comment.decode($0).value }
default: return []
}
```

**Comment by gfontenot** [comment]
Note that another way to accomplish this would be to use a custom parser that you `flatMap` into the pipeline:

```swift
j <|| "comments" >>- { pure($0.map { Comment.decode($0).value }) }
```

(types might be slightly off, but that's the general idea.)

**Comment by alcarvalho** [comment]
@tonyd256 ok, I understand what you're saying. I am sure you want to stay away from more complexity.

That being said, I have changed my mind about the array of optionals, because I thought that just ignoring (filtering) the objects that did not decode from the array in the first place would be even better, as I stated in the first comment.

This is why the operator has the exact same signature as the `<||` because it produces the same array type, but ignoring errors of each value decoded. That's also what I meant by "resilient". ;)

But I am totally ok if you think that this is not a good thing to be added.

@gfontenot thank you for that line. That will be helpful in case you don't want to accept this implementation. :)

**Comment by gfontenot** [comment]
> I have changed my mind about the array of optionals, because I thought that just ignoring (filtering) the objects that did not decode from the array in the first place would be even better, as I stated in the first comment.

FWIW: This can be done quickly by throwing a [`concatOptionals`](https://github.com/thoughtbot/ExtendedArray) into the mix:

```swift
j <|| "comments" >>- { pure(concatOptionals($0.map { Comment.decode($0).value })) }
```

Also, note that this can easily be generalized to a small custom parser function:

```swift
func decodeFilteredArray<T: Decodable where T == T.DecodedType>(js: [JSON]) -> Decoded<[T]> {
  return pure(concatOptionals(js.map { T.decode($0).value }))
}
```

That'll work for any array of objects that are decodable.

**Comment by alcarvalho** [comment]
Thanks again, @gfontenot! 

So it seems that you guys think this is a bad idea, so I am cloning this PR. ;)

**Comment by gfontenot** [comment]
@alcarvalho Just to be clear, we don't think this is a bad idea at all. We just want to be careful about keeping the main lib focused. For things like this, we prefer educating users on how to build their own solutions that work _with_ Argo.

**Comment by alcarvalho** [comment]
That totally makes sense! You have been very supportive to me. Thanks! ;)

**Pull request closed without merging**
