### PR TITLE
Try to fix how Runes and Curry are included so things build.

### PR DESCRIPTION
**Pull request by sgoodwin**
I think this should fix the issue with module not found errors for apps using Argo.

### CODE REVIEW

**Comment by gfontenot** [comment]
Hard to tell from the diff: Is this just adding the Carthage build folder to the framework search paths?

My concern in "fixing" this like this is that this is _only_ a problem when using Argo with Carthage and submodules. No other configuration has any issues. Once the checkout dir is symlinked for submodules the way it is for normal checkouts this issue will dissapear.

**Comment by sgoodwin** [comment]
Oh, so you still want to do Runes and Curry as submodules?

I went through and pointed all those framework references in the workspace file to their places in ```Carthage/Build``` so they'd build fine. Even Argo by itself wouldn't build for all targets before that. If this doesn't help, then no worries.

**Comment by gfontenot** [comment]
No, sorry. Argo itself should be building fine with Carthage assuming you're using 0.18+. The issue that we've been talking about in #412 is limited to users using `carthage --use-submodules`. That's the only time (AFAIK) that building is broken. So since that's a bug in Carthage, I was wondering if it was something we should be working around on our end.

**Comment by sgoodwin** [comment]
For our project, we have to add '''--platform iOS''' to keep it from trying to build for WatchKit and such and fail.

**Comment by mdiep** [comment]
> So since that's a bug in Carthage

There's a PR open for that, btw. (https://github.com/Carthage/Carthage/pull/1493)

Hopefully we can get it reviewed, merged, and released in the next week.

**Comment by gfontenot** [comment]
@sgoodwin that sounds like a new issue that I haven't seen reported yet. Mind opening an issue so we can discuss?

@mdiep 🎉

**Comment by sgoodwin** [comment]
Will do later today.

**Pull request closed without merging**
