### PR TITLE
implement native submodules instead of requiring external dep manager

### PR DESCRIPTION
**Pull request by sebbean**
seems strange to require someone to use a package manager when submodules are baked right into git. 
They're pretty darn simple once you start using them.

### CODE REVIEW

**Comment by kaishin** [comment]
> They're pretty darn simple once you start using them.

I couldn't disagree more. Never had a fun time using submodules. Package managers are the proper way to deal with software dependencies because they abstract the git implementation details and encourage authors to use semantic versioning.

**Comment by gfontenot** [comment]
Agree with @kaishin. We don't require Carthage to _use_ Argo, which is the important thing. Development dependencies are development dependencies. There's nothing strange about using them. I very much dislike git submodules, and have no interest in (re-)introducing them here.

**Comment by sebbean** [comment]
You do require *something* to pull in Runes and Box. Otherwise Argo will not build.

**Comment by sebbean** [comment]
yea, i guess what's great about submodules is you can very easily create pull requests for the projects that are deps and fix code that may need fixing. 
creates a very clean flow to push upstream to external open source projects.

it's really just git inside git.

i was all about dep managers up until cocoapods fell apart. carthage wasn't really doing anything for anyone.. just adding confusion. thought it was about time to figure out a real solution.

not that this is the venue but i'd love to hear some of your issues with them. i find it as a great way to deal with interdependent projects while keeping them in separate repo.

**Comment by sebbean** [comment]
curious what you mean by not *requiring* carthage since there's no other way to pull in the dependencies that Argo requires. @gfontenot

**Comment by gfontenot** [comment]
@sebbean We support Carthage and CocoaPods as client-side dependency management solutions, as well as provide prebuilt binaries for the dependencies we control (Argo and Runes). Box is also offered as a prebuilt binary. Our support of git submodules as an installation method is incidental (and [kind of broken][#121]). I'm interested in finding a way to support git submodules as a dependency solution, but not incredibly interested in bloating our repo and complicating our development process to accommodate it.

[#121]: https://github.com/thoughtbot/Argo/issues/121

**Comment by gfontenot** [comment]
Maybe I'm being too dogmatic about this. I'm going to re-open for now. I'll continue thinking about this and we can continue the discussion.

**Comment by gfontenot** [comment]
I'm closing this again in favor of the more comprehensive change in #123. We will use git submodules moving forward, assuming that PR gets merged.

**Comment by sebbean** [comment]
thanks for the reconsideration @gfontenot 

funnily enough i see git submodules as significantly less complicated than attempting to learn and understand what another dep manager is attempting to do and how it's doing it.

i spent a fair amount of time with carthage after realizing cocoapods wasn't up to the task (few months back before they figured it out). I realized that I actually had no idea what any of these things were actually doing and I was relying too much on them to put my project / workspaces together. 

Since moving to submodules, I've allowed myself to work through the process of adding any type of dependencies to my project without the reliance on another system. I now am much more comfortable debugging framework / library related issues that were completely beyond me in the days of blind cocopods usage.

Not to mention the amount of PR's I've created with minor fixes to open source projects (dependencies) since the workflow is painless. Takes me 2 minutes to fix a lil warning or bug and push up to be reviewed. This PR included!

I think that, although it may not be for everyone, becoming more comfortable with this flow would not only help end users understand how projects *actually* interact with each other, it would also significantly increase end user contributions to projects that they are dependent on.

**Pull request closed without merging**
