### PR TITLE
[Don't merge] Argo can't be used with SwiftPM

### PR DESCRIPTION
**Pull request by ikesyo**
⚠️ __This is a demo__ ⚠️ 

I'm not sure why but Argo can't be used with SwiftPM on macOS currently. See https://travis-ci.org/ikesyo/Argo/builds/174070096 for the detailed errors.

### CODE REVIEW

**Comment by ikesyo** [comment]
Any thoughts?

**Comment by gfontenot** [comment]
Sorry for the delay here @ikesyo! I haven't had time to look into this yet. I'm not ignoring it and will hopefully have time to get to it soon.

**Comment by RLovelett** [comment]
I was running into the same issue and I reported it on the [swift-build-dev](https://lists.swift.org/pipermail/swift-build-dev/Week-of-Mon-20161128/000760.html) mailing list.

The reason I decided to go there was if I did `swift package generate-xcodeproj` and built from Xcode it worked. I thought it might be a configuration issue with my `Package.swift` or with SwiftPM itself.

Just thought I'd share.

**Comment by gfontenot** [comment]
Thanks for the notes, y'all. I was able to narrow this down and have opened #436 on our end as a fix. I should hopefully have that merged in soon and will be shipping a release to fix SPM alongside #428.

I also submitted my findings [to the swift-build-dev mailing list](https://lists.swift.org/pipermail/swift-build-dev/Week-of-Mon-20161128/000768.html)

**Pull request closed without merging**
