### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlexanderKaraberov**
Added info and workaround for the known issue with Swift compiler: "Expression was too complex to be solved in reasonable time; consider breaking up into distinct sub-expressions". It will be reasonable to create a separate file "Known Issues" if there will be more problems which have solutions.

### CODE REVIEW

**Comment by tonyd256** [comment]
Thanks for this! We know there is a lack of documentation for Argo and we want to tackle it at some point so these kinds of contributions are awesome! I'll review it soon and get back to you.

for reference #92

**Comment by tonyd256** [comment]
Would you mind actually moving this into a separate file: `Documentation/Known-Issues.md`? Then you can reference it from `Documentation/README.md`

**Comment by AlexanderKaraberov** [comment]
Of course no.
I just wanted such kind of information was accessible in some way to avoid further confusions.

**Comment by tonyd256** [comment]
I need to merge in the documentations branch to keep master up to date. That will automatically close this PR but would you mind re-opening this PR on master?

**Pull request closed without merging**
