### PR TITLE
Pin Runes to version 1.1.1 for 0.3.x

### PR DESCRIPTION
**Pull request by gfontenot**
Since we weren't pinning the version of Runes with Carthage, users were
getting the version of Runes compatible with Swift 1.2, which obviously
isn't what we wanted. Pinning this to 1.1.1 will ensure that doesn't
happen in the future.

This also makes the same changes to the project that we did for master,
removing the submodules and using the binaries provided by Carthage.

### CODE REVIEW

**Comment by felixjendrusch** [comment]
That was quick! :+1:

**Comment by tonyd256** [comment]
:+1:

**Comment by Keithbsmiley** [comment]
:+1:

**Comment by felixjendrusch** [comment]
Just for reference, [here](https://github.com/Carthage/Carthage/issues/339) is the original issue.

**Pull request merged**
