### PR TITLE
Explicitly code sign framework

### PR DESCRIPTION
**Pull request by sidraval**
Carthage is unhappy without this, ala https://github.com/thoughtbot/Swish/pull/3

### CODE REVIEW

**Comment by tonyd256** [comment]
Interesting .. is this new? Also, does this cover us for OS X and watchOS?

**Comment by sidraval** [comment]
Yeah, @gfontenot had problems installing Swish via Carthage, and I'm having problems installing Argo via Carthage now.

@gfontenot mentioned in Slack that it might be an XCode bug... but this seems to help for now?

I'm not sure about OSX/watchOS.

**Comment by gfontenot** [comment]
We need to do this for watchOS as well, but not for OS X

**Comment by sidraval** [comment]
@tonyd256 @gfontenot Any other comments / questions?

**Comment by gfontenot** [comment]
@sidraval Can you make this change for the watchOS target as well?

**Comment by sidraval** [comment]
@gfontenot I made the change at the `Argo` project level, not at the specific iOS target level, so does this already apply to the watchOS target?

When I select the watchOS target specifically, I see its `Code Signing Identity` set to `iOS Developer` already.

**Comment by gfontenot** [comment]
Ah, I didn't pull the project down to check.

We should be setting this at the target level, not the project level. Setting it at the project level will (I believe) cause issues for the Mac target.

**Comment by sidraval** [comment]
@gfontenot Alright, I made it for both the `Argo-iOS` and `Argo-watchOS` targets individually.

**Comment by gfontenot** [comment]
:+1: merge away

**Pull request merged**
