### PR TITLE
Remove `CustomStringConvertible` constraint on `typeMismatch` function

### PR DESCRIPTION
**Pull request by dapenggao**
According to Apple's [documentation](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_CustomStringConvertible_Protocol/index.html) of `CustomStringConvertible`: 
> `String(instance)` will work for an `instance` of _any_ type, returning its `description` if the `instance` happens to be `CustomStringConvertible`. Using `CustomStringConvertible` as a generic constraint, or accessing a conforming type's `description` directly, is therefore discouraged.

Hence we can unify the `typeMismatch` function so that it accepts _any_ types.

### CODE REVIEW

**Comment by tonyd256** [comment]
I like this :+1: ... snuck in some other clean up stuff but I like those too.

**Comment by gfontenot** [comment]
This is great. Can you move that explanation you provided into body of the git commit message and then I'm happy to merge this in?

**Comment by gfontenot** [comment]
If you could also rebase on master while your at it, that'll fix CI for this PR.

**Comment by dapenggao** [comment]
Done here. Added explanation and CI passes.

**Comment by dapenggao** [comment]
Any updates on this?

**Comment by gfontenot** [comment]
I'm not sure what happened here, but it looks like your fork is no longer available? That's preventing me from being able to merge it.

**Comment by dapenggao** [comment]
Sorry about that. I'll open another PR.

**Pull request closed without merging**
