### PR TITLE
Work around memory leak with switch and as patterns.

### PR DESCRIPTION
**Pull request by paulyoung**
This pull request employs the workaround suggested by @jckarter in https://github.com/thoughtbot/Argo/issues/205 on the chance that it's deemed necessary.

### CODE REVIEW

**Comment by paulyoung** [comment]
Similar changes should probably also be made where `switch` and `as` is used in [StandardTypes](https://github.com/thoughtbot/Argo/blob/4b71fa487b9d81aee458049867f1b89e20c526d9/Argo/Types/StandardTypes.swift):

* [`n as Int`](https://github.com/thoughtbot/Argo/blob/4b71fa487b9d81aee458049867f1b89e20c526d9/Argo/Types/StandardTypes.swift#L16)
* [`n as Double`](https://github.com/thoughtbot/Argo/blob/4b71fa487b9d81aee458049867f1b89e20c526d9/Argo/Types/StandardTypes.swift#L34)
* [`n as Bool`](https://github.com/thoughtbot/Argo/blob/4b71fa487b9d81aee458049867f1b89e20c526d9/Argo/Types/StandardTypes.swift#L43)
* [`n as Float`](https://github.com/thoughtbot/Argo/blob/4b71fa487b9d81aee458049867f1b89e20c526d9/Argo/Types/StandardTypes.swift#L52)

**Comment by paulyoung** [comment]
Actually, I don't think the bug applies in the places I linked above, so this might be good to go.

**Comment by RuiAAPeres** [comment]
:+1:

**Comment by tonyd256** [comment]
Thanks for this @paulyoung! Merged in here: bd34d358024a253af30fab92dff3c117269abe0d

**Comment by RuiAAPeres** [comment]
@tonyd256 @paulyoung can confirm from my side the leaks are gone. 
screen shot 2015-09-14 at 22 04 26

**Comment by tonyd256** [comment]
Awesome!!

**Comment by paulyoung** [comment]
Hopefully we can `git revert bd34d358024a253af30fab92dff3c117269abe0d` sometime soon.

**Comment by jshier** [comment]
@paulyoung @tonyd256 @RuiAAPeres Looks like this may be fixed in Xcode 7.1 beta 2. From the release notes: • Using switch against multiple types with as patterns no longer causes a memory leak. (22587077)

**Comment by tonyd256** [comment]
ya just read that :tada: !! but we'll have to wait for 7.1 to land

**Pull request closed without merging**
