### PR TITLE
Update Cartfile to use version 1.2.2 or newer of Box.

### PR DESCRIPTION
**Pull request by Nirma**
Set the version of Box to be 1.2.2 or greater in the Cartfile.

### CODE REVIEW

**Comment by gfontenot** [comment]
What's the reasoning behind this change?

**Comment by Nirma** [comment]
Sorry, I should have been more specific!

There were occasionally build errors present in versions of box before 1.2.2 as explained in the release notes for 1.2.2:
https://github.com/robrix/Box/releases

My hopes in submitting this pull request were to make sure it was using the latest stable version of Box.

**Comment by tonyd256** [comment]
@Nirma Thanks for the PR! We still want to use the pessimism operator, but I amended your commit to start at `1.2.2` here: e5536a036fab42f3cc5d7f1c81d747e6f5b8c1fc

**Comment by Nirma** [comment]
@tonyd256 Thank you so much!

**Pull request closed without merging**
