### PR TITLE
Add Contributing/Code of Conduct

### LINKED ISSUE #91: Add a CONTRIBUTING.md and code of conduct

### PR DESCRIPTION
**Pull request by gfontenot**
Fixes #91

### CODE REVIEW

**Comment by gfontenot** [comment]
This is waiting on the Code of Conduct //cc @mxie

**Comment by tonyd256** [comment]
:+1:

**Comment by mxie** [comment]
The Open Source CoC is now live at https://thoughtbot.com/open-source-code-of-conduct!

**Comment by gfontenot** [comment]
Done

**Pull request merged**
