### PR TITLE
watchOS framework target

### PR DESCRIPTION
**Pull request by JaviSoto**

### CODE REVIEW

**Comment by JaviSoto** [comment]
>Simulator verification failed." UserInfo=0x7fe68ab30480 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}

Is CI supposed to be working?

**Comment by tonyd256** [comment]
Not with Swift 2

**Comment by tonyd256** [comment]
@JaviSoto Thanks for this!

**Comment by JaviSoto** [comment]
Thank you!

**Pull request merged**
