### PR TITLE
Better Swift 2.3/Xcode 8 support

### PR DESCRIPTION
**Pull request by ikesyo**
Continuing from https://github.com/thoughtbot/Argo/pull/379#issuecomment-234014256. 🙏

### CODE REVIEW

**Comment by gfontenot** [comment]
That CI failure is expected, fwiw.

**Comment by gfontenot** [comment]
Thanks! Is there anything else that should be in this new release, or should I cut 3.0.3?

**Comment by ikesyo** [comment]
You too! This should be enough for the new release. 😄

**Comment by gfontenot** [comment]
👍 Killer. This has been released as 3.0.3.

**Pull request merged**
