### PR TITLE
Add carthage compatible badge

### PR DESCRIPTION
**Pull request by tonyd256**
Want to add this in. The placement is up for discussion. Any opinions?

### CODE REVIEW

**Comment by gfontenot** [comment]
The convention I've seen is to put it at the very top of the README.

**Comment by tonyd256** [comment]
I've seen that as well but also seen things mixed in so ya

**Comment by tonyd256** [comment]
@gfontenot is this better placement?

**Comment by gfontenot** [comment]
I like that better, yeah. Want to open one of these for Runes as well?

**Pull request merged**
