### PR TITLE
Bring back CI with Circle-CI

### PR DESCRIPTION
**Pull request by tonyd256**

### CODE REVIEW

**Comment by gfontenot** [comment]
...how does this work without Carthage?

**Comment by gfontenot** [comment]
Oh, the carthage stuff is set up on Circle itself. That weirds me out.

**Comment by tonyd256** [comment]
@gfontenot I agree that I would like to be using bin/setup here but Circle-ci is having the same damn permissions issues that mark was having with carthage ... so I forced it to compile the Mac side only so it will work

**Comment by gfontenot** [comment]
:+1:

**Pull request merged**
