### PR TITLE
Feature/json encodable

### PR DESCRIPTION
**Pull request by nvh**
As discussed in #42 this is an implementation of JSONEncodable.

A question I encountered is what should happen to optional values when represented in a JSON object. It's possible to include the key, but and make the value `null` or just remove the key entirely. I chose to include the keys and make it easy to filter them afterwards.

Let me know what you think!

### CODE REVIEW

**Comment by gfontenot** [comment]
I'm still honestly not sure why this is useful. It seems like this is a lot of code (and boilerplate) to add for creating dictionary representations of your models. We haven't seen the need to move from a model back to `JSONValue`. Where are you running into this?

**Comment by nvh** [comment]
When sending objects back to the server, I want to be sure that the data that I provide to the JSON serialisation, is actually of the correct type at compile time.

**Comment by gfontenot** [comment]
That's good in theory, but you aren't gaining that here. There's no difference at compile time between the types `JSONValue.JSONString("foo")` and `JSONValue.JSONNumber(2)`. In order to get some kind of compile-time check on your JSON, you'd need to have a stronger type system than Swift allows.

**Comment by gfontenot** [comment]
@nvh Did you have any other thoughts on this?

**Comment by nvh** [comment]
True, but there is a difference between trying to encode

```swift
struct Thing {
  let date: NSDate
  let color: UIColor 
  func encode() -> AnyObject {
     ["date":date,"color":color]
  }
}
```
This will compile and run fine, and probably turn into json too, but you have no control on how it will do so, while if the protocol is

```swift
  func encode() -> JSONValue {
     ["date":date,"color":color]
  }
```
The compiler will complain that NSDate and UIColor are not JSONEncodable and you will have to specify explicitly how to convert them to something that can be JSON encoded.

**Comment by tonyd256** [comment]
I get what you're saying but that seems like the only value we'd be getting from adding this. I have a couple thoughts.

I don't think the benefits outweigh the bloat from the code additions and the overhead for a user to implement this. If we could use this to guarantee type safety of the resulting JSON then I think it would be awesome, but because of JSON's dynamic nature and the fact that the API backend is what controls the types needed, I think this would be better suited for tests in the UnitTest bundle.

Also, when I'm thinking of the scope of Argo, I see it as a framework for translating JSON into model objects. This is the core of Argo and the reason for it being built. More over than type safety, it is non trivial to parse JSON (dynamically typed) into Swift (static typed) model so that's the biggest benefit it can provide. Going the other way around is easier to put together without Argo. I don't think Swift can provide the type safety we'd like if we were to add this.

However, I do think this is an interesting problem and could be better suited as a separate framework that either used Argo as a dependency or came up with a better version of `JSONValue` that we could share.

Thanks for putting in the work, but I'm going to close this for now because it's out of scope for Argo.

**Comment by vesterbaek** [comment]
@nvh I think your contributions here are useful. Have you considered making an "Argo-encode" library for this?

**Comment by nvh** [comment]
@vesterbaek Yes, that was actually my next step, but I havent gotten to it yet

**Pull request closed without merging**
