### PR TITLE
Adding specific Int64 type support 

### PR DESCRIPTION
**Pull request by MichaelMcGuire**
On 32-bit platforms (namely iPhone 4S, iPhone 5 for iOS8+) the Swift Int type only goes up to 2^31.  Even though there is technically no limits placed upon JSON numeric values, they are often designed around JavaScript clients which have a maximum integer value of 2^53.  I've added explicit support for the Int64 type to support this limit.  

In order to get around Xcode 6.3/Swift 1.2 (see #106) limitations, I split out the numeric tests into a sub-model.  Using the solution presented in #5 didn't seem to work.

### CODE REVIEW

**Comment by MichaelMcGuire** [comment]
Probably important to mention that if a numeric value of greater than 2^31 is present in the data and you are on a 32-bit device using a plain Int type, you get a silent overflow on decoding.

**Comment by gfontenot** [comment]
Killer. I'm going to reword your commit message to include some of the info you've provided here and then merge it in.

**Comment by gfontenot** [comment]
Done in ddee5da

**Comment by MichaelMcGuire** [comment]
Awesome, thanks!

**Pull request closed without merging**
